#!/bin/bash
tmux new -s sicp -n racket 'cd /data/repos/manhtai/course-sicp/exercises; fish' \; splitw -h -p 45 -t 1 -c '/data/repos/manhtai/course-sicp/exercises' 'racket -i -l xrepl -l sicp-racket' \; selectp -t 1 \; attach
